json.id summoner_info.id
json.puuid summoner_info.puuid
json.tier summoner_info.tier
json.rank summoner_info.rank
json.league_points summoner_info.league_points
json.riot_summoner_id summoner_info.riot_summoner_id
json.summoner_name summoner_info.summoner_name
json.wins summoner_info.wins
json.losses summoner_info.losses
